@HostedServiceWebApp_HostAddress = http://localhost:5238

POST {{HostedServiceWebApp_HostAddress}}/basic

###

GET {{HostedServiceWebApp_HostAddress}}/reusable/reusable-8d951e9d-e058-567a-bc43-fc7fa843b359

###

POST {{HostedServiceWebApp_HostAddress}}/recovering

###

POST {{HostedServiceWebApp_HostAddress}}/resilient

###


